# Site Ayarları
title: Örnek Site
email: kullanci@domain.com
description: >
  Siteniz ile ilgili açıklama
  yazabilirsiniz!
timezone: Europe/Istanbul
locale: tr # Türkçe

baseurl: ""                                  # Eğer varsa alt dizin, örnek: /blog/
url: "http://domain.com/"                    # Sitenizin adresi
tags_url: "etiketler"                        # Etiketler için alt dizin adı
twitter_username: hesap                      # varsa Twitter kullanıcı adı
github_username:  hesap                      # varsa GitHub kullanıcı adı
speakerdeck_username: hesap                  # varsa SpeakerDeck kullanıcı adı
disqus_shortname: hesap                      # varsa Disqus kullanıcı adı (yorum mekanizması için)

header-img: images/example/home-bg.jpg
header-logo: images/example/logo.png

footer_address: |
  Adres Satır 1
  Adres Satır 2
  Adres Satır 3

# Html Üretme Ayarları
markdown: redcarpet
paginate: 5
paginate_path: /sayfa/:num/
exclude: [vendor, Rakefile, Gemfile]
