# Site settings
title: Aslanoba Labs
email: your-email@domain.com
description: >
  Yazılım geliştirici merkezine hoş geldiniz! Faaliyetlerimizden haberdar
  olmak için e-posta listemize kayıt olun!
timezone: Europe/Istanbul
locale: tr # Türkçe

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://labs.aslanobagroup.com/"
twitter_username: aslanobalabs
github_username:  aslanobalabs
speakerdeck_username: aslanobalabs
header-img: images/home-bg.jpg

# Build settings
markdown: redcarpet
paginate: 5
paginate_path: /sayfa/:num/
exclude: [vendor, Rakefile, Gemfile]
